import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { useSession, signOut } from "@/lib/auth-client";
import { useState } from "react";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const { data: session, isPending } = useSession();
  const router = useRouter();
  const [from, setFrom] = useState("");
  const [to, setTo] = useState("");
  const [days, setDays] = useState("");
  const [stops, setStops] = useState("");
  const [loading, setLoading] = useState(false);

  const handleSignOut = async () => {
    await signOut();
  };

  const handleOpenCanvas = async () => {
    setLoading(true);
    try {
      const response = await fetch("/api/generate-travel-flow", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ from, to, days: Number(days), stops }),
      });

      const result = await response.json();
      
      if (result.success) {
        router.push({
          pathname: "/canvas",
          query: { flowData: JSON.stringify(result.data.flow) },
        });
      } else {
        alert("Failed to generate travel flow");
      }
    } catch (error) {
      console.error("Error:", error);
      alert("An error occurred");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Next.js on Replit!</h1>

        {isPending ? (
          <p className={styles.description}>Loading...</p>
        ) : session?.user ? (
          <div>
            <p className={styles.description}>
              Welcome, {String(session.user.name || session.user.email || "User")}!
            </p>
            <div style={{ marginTop: "20px", maxWidth: "500px", margin: "0 auto" }}>
              <div style={{ marginBottom: "15px" }}>
                <input
                  type="text"
                  placeholder="From (e.g., Delhi)"
                  value={from}
                  onChange={(e) => setFrom(e.target.value)}
                  style={{
                    width: "100%",
                    padding: "10px",
                    fontSize: "14px",
                    borderRadius: "5px",
                    border: "1px solid #ccc",
                  }}
                />
              </div>
              <div style={{ marginBottom: "15px" }}>
                <input
                  type="text"
                  placeholder="To (e.g., Goa)"
                  value={to}
                  onChange={(e) => setTo(e.target.value)}
                  style={{
                    width: "100%",
                    padding: "10px",
                    fontSize: "14px",
                    borderRadius: "5px",
                    border: "1px solid #ccc",
                  }}
                />
              </div>
              <div style={{ marginBottom: "15px" }}>
                <input
                  type="number"
                  placeholder="Days (e.g., 7)"
                  value={days}
                  onChange={(e) => setDays(e.target.value)}
                  style={{
                    width: "100%",
                    padding: "10px",
                    fontSize: "14px",
                    borderRadius: "5px",
                    border: "1px solid #ccc",
                  }}
                />
              </div>
              <div style={{ marginBottom: "20px" }}>
                <input
                  type="text"
                  placeholder="Stops (optional, e.g., Mumbai, Pune)"
                  value={stops}
                  onChange={(e) => setStops(e.target.value)}
                  style={{
                    width: "100%",
                    padding: "10px",
                    fontSize: "14px",
                    borderRadius: "5px",
                    border: "1px solid #ccc",
                  }}
                />
              </div>
              <div style={{ display: "flex", gap: "10px", justifyContent: "center" }}>
                <button
                  onClick={handleOpenCanvas}
                  disabled={loading}
                  style={{
                    padding: "10px 20px",
                    fontSize: "16px",
                    backgroundColor: loading ? "#ccc" : "#0070f3",
                    color: "white",
                    border: "none",
                    borderRadius: "5px",
                    cursor: loading ? "not-allowed" : "pointer",
                  }}
                >
                  {loading ? "Generating..." : "Open Canvas"}
                </button>
                <button
                  onClick={handleSignOut}
                  style={{
                    padding: "10px 20px",
                    fontSize: "16px",
                    backgroundColor: "#ff0000",
                    color: "white",
                    border: "none",
                    borderRadius: "5px",
                    cursor: "pointer",
                  }}
                >
                  Sign Out
                </button>
              </div>
            </div>
          </div>
        ) : (
          <div>
            <p className={styles.description}>
              Please <Link href="/login">sign in</Link> or{" "}
              <Link href="/signup">sign up</Link> to continue.
            </p>
          </div>
        )}

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://docs.replit.com/category/deployments"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>After you are happy with this app, deploy it on Replit!</p>
          </a>
        </div>
      </main>
    </div>
  );
};

export default Home;
