import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { useSession, signOut } from "@/lib/auth-client";
import { useState, useEffect } from "react";
import styles from "../styles/Home.module.css";

interface Trip {
  id: string;
  name: string;
  fromLocation: string;
  toLocation: string;
  days: string;
  stops: string | null;
  createdAt: string;
}

const Home: NextPage = () => {
  const { data: session, isPending } = useSession();
  const router = useRouter();
  const [from, setFrom] = useState("");
  const [to, setTo] = useState("");
  const [days, setDays] = useState("");
  const [stops, setStops] = useState("");
  const [name, setName] = useState("");
  const [loading, setLoading] = useState(false);
  const [showModal, setShowModal] = useState(false);
  const [trips, setTrips] = useState<Trip[]>([]);
  const [loadingTrips, setLoadingTrips] = useState(false);

  useEffect(() => {
    if (session?.user) {
      fetchTrips();
    }
  }, [session]);

  const fetchTrips = async () => {
    setLoadingTrips(true);
    try {
      const response = await fetch("/api/trips/list");
      const result = await response.json();
      if (result.success) {
        setTrips(result.trips);
      }
    } catch (error) {
      console.error("Error fetching trips:", error);
    } finally {
      setLoadingTrips(false);
    }
  };

  const handleSignOut = async () => {
    await signOut();
  };

  const handleCreateTrip = async () => {
    setLoading(true);
    try {
      const response = await fetch("/api/trips/create", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ from, to, days: Number(days), stops, name }),
      });

      const result = await response.json();
      
      if (result.success) {
        setShowModal(false);
        setFrom("");
        setTo("");
        setDays("");
        setStops("");
        setName("");
        fetchTrips();
        router.push(`/canvas?tripId=${result.tripId}`);
      } else {
        alert("Failed to generate travel flow");
      }
    } catch (error) {
      console.error("Error:", error);
      alert("An error occurred");
    } finally {
      setLoading(false);
    }
  };

  const handleViewTrip = (tripId: string) => {
    router.push(`/canvas?tripId=${tripId}`);
  };

  const handleDeleteTrip = async (tripId: string, tripName: string, e: React.MouseEvent) => {
    e.stopPropagation();
    
    if (!confirm(`Are you sure you want to delete "${tripName}"?`)) {
      return;
    }

    try {
      const response = await fetch("/api/trips/delete", {
        method: "DELETE",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ id: tripId }),
      });

      const result = await response.json();
      
      if (result.success) {
        fetchTrips();
      } else {
        alert("Failed to delete trip");
      }
    } catch (error) {
      console.error("Error deleting trip:", error);
      alert("An error occurred while deleting");
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Next.js on Replit!</h1>

        {isPending ? (
          <p className={styles.description}>Loading...</p>
        ) : session?.user ? (
          <div>
            <p className={styles.description}>
              Welcome, {String(session.user.name || session.user.email || "User")}!
            </p>
            <div style={{ marginTop: "20px", display: "flex", gap: "10px", justifyContent: "center" }}>
              <button
                onClick={() => setShowModal(true)}
                style={{
                  padding: "12px 30px",
                  fontSize: "16px",
                  backgroundColor: "#0070f3",
                  color: "white",
                  border: "none",
                  borderRadius: "5px",
                  cursor: "pointer",
                  fontWeight: "600",
                }}
              >
                New Trip
              </button>
              <button
                onClick={handleSignOut}
                style={{
                  padding: "10px 20px",
                  fontSize: "16px",
                  backgroundColor: "#ff0000",
                  color: "white",
                  border: "none",
                  borderRadius: "5px",
                  cursor: "pointer",
                }}
              >
                Sign Out
              </button>
            </div>

            {/* Trips List */}
            <div style={{ marginTop: "40px", maxWidth: "800px", margin: "40px auto" }}>
              <h2 style={{ marginBottom: "20px", color: "#333" }}>Your Trips</h2>
              {loadingTrips ? (
                <p>Loading trips...</p>
              ) : trips.length === 0 ? (
                <p style={{ color: "#666" }}>No trips yet. Create your first trip!</p>
              ) : (
                <div style={{ display: "grid", gap: "15px" }}>
                  {trips.map((trip) => (
                    <div
                      key={trip.id}
                      onClick={() => handleViewTrip(trip.id)}
                      style={{
                        padding: "20px",
                        backgroundColor: "#fff",
                        border: "1px solid #ddd",
                        borderRadius: "8px",
                        cursor: "pointer",
                        transition: "all 0.2s",
                        boxShadow: "0 2px 4px rgba(0,0,0,0.05)",
                        position: "relative",
                      }}
                      onMouseEnter={(e) => {
                        e.currentTarget.style.boxShadow = "0 4px 12px rgba(0,0,0,0.1)";
                        e.currentTarget.style.borderColor = "#0070f3";
                      }}
                      onMouseLeave={(e) => {
                        e.currentTarget.style.boxShadow = "0 2px 4px rgba(0,0,0,0.05)";
                        e.currentTarget.style.borderColor = "#ddd";
                      }}
                    >
                      <button
                        onClick={(e) => handleDeleteTrip(trip.id, trip.name, e)}
                        style={{
                          position: "absolute",
                          top: "15px",
                          right: "15px",
                          padding: "6px 12px",
                          fontSize: "12px",
                          backgroundColor: "#ff4444",
                          color: "white",
                          border: "none",
                          borderRadius: "4px",
                          cursor: "pointer",
                          fontWeight: "500",
                          transition: "background-color 0.2s",
                        }}
                        onMouseEnter={(e) => {
                          e.currentTarget.style.backgroundColor = "#cc0000";
                        }}
                        onMouseLeave={(e) => {
                          e.currentTarget.style.backgroundColor = "#ff4444";
                        }}
                      >
                        Delete
                      </button>
                      <h3 style={{ margin: "0 0 10px 0", color: "#333", paddingRight: "80px" }}>{trip.name}</h3>
                      <p style={{ margin: "5px 0", color: "#666", fontSize: "14px" }}>
                        <strong>Route:</strong> {trip.fromLocation} → {trip.toLocation}
                      </p>
                      <p style={{ margin: "5px 0", color: "#666", fontSize: "14px" }}>
                        <strong>Duration:</strong> {trip.days} days
                      </p>
                      {trip.stops && (
                        <p style={{ margin: "5px 0", color: "#666", fontSize: "14px" }}>
                          <strong>Stops:</strong> {trip.stops}
                        </p>
                      )}
                      <p style={{ margin: "10px 0 0 0", color: "#999", fontSize: "12px" }}>
                        Created: {new Date(trip.createdAt).toLocaleDateString()}
                      </p>
                    </div>
                  ))}
                </div>
              )}
            </div>

            {showModal && (
              <div
                style={{
                  position: "fixed",
                  top: 0,
                  left: 0,
                  right: 0,
                  bottom: 0,
                  backgroundColor: "rgba(0, 0, 0, 0.5)",
                  display: "flex",
                  justifyContent: "center",
                  alignItems: "center",
                  zIndex: 1000,
                }}
                onClick={() => setShowModal(false)}
              >
                <div
                  style={{
                    backgroundColor: "white",
                    padding: "30px",
                    borderRadius: "10px",
                    maxWidth: "500px",
                    width: "90%",
                    boxShadow: "0 4px 20px rgba(0, 0, 0, 0.2)",
                  }}
                  onClick={(e) => e.stopPropagation()}
                >
                  <h2 style={{ marginTop: 0, marginBottom: "20px", color: "#333" }}>
                  Plan Your Trip
                  </h2>
                  <div style={{ marginBottom: "15px" }}>
                  <input
                  type="text"
                  placeholder="Trip Name (optional)"
                  value={name}
                  onChange={(e) => setName(e.target.value)}
                  style={{
                  width: "100%",
                  padding: "10px",
                  fontSize: "14px",
                  borderRadius: "5px",
                  border: "1px solid #ccc",
                  }}
                  />
                  </div>
                  <div style={{ marginBottom: "15px" }}>
                    <input
                      type="text"
                      placeholder="From (e.g., Delhi)"
                      value={from}
                      onChange={(e) => setFrom(e.target.value)}
                      style={{
                        width: "100%",
                        padding: "10px",
                        fontSize: "14px",
                        borderRadius: "5px",
                        border: "1px solid #ccc",
                      }}
                    />
                  </div>
                  <div style={{ marginBottom: "15px" }}>
                    <input
                      type="text"
                      placeholder="To (e.g., Goa)"
                      value={to}
                      onChange={(e) => setTo(e.target.value)}
                      style={{
                        width: "100%",
                        padding: "10px",
                        fontSize: "14px",
                        borderRadius: "5px",
                        border: "1px solid #ccc",
                      }}
                    />
                  </div>
                  <div style={{ marginBottom: "15px" }}>
                    <input
                      type="number"
                      placeholder="Days (e.g., 7)"
                      value={days}
                      onChange={(e) => setDays(e.target.value)}
                      style={{
                        width: "100%",
                        padding: "10px",
                        fontSize: "14px",
                        borderRadius: "5px",
                        border: "1px solid #ccc",
                      }}
                    />
                  </div>
                  <div style={{ marginBottom: "20px" }}>
                    <input
                      type="text"
                      placeholder="Stops (optional, e.g., Mumbai, Pune)"
                      value={stops}
                      onChange={(e) => setStops(e.target.value)}
                      style={{
                        width: "100%",
                        padding: "10px",
                        fontSize: "14px",
                        borderRadius: "5px",
                        border: "1px solid #ccc",
                      }}
                    />
                  </div>
                  <div style={{ display: "flex", gap: "10px", justifyContent: "flex-end" }}>
                    <button
                      onClick={() => setShowModal(false)}
                      style={{
                        padding: "10px 20px",
                        fontSize: "16px",
                        backgroundColor: "#ccc",
                        color: "#333",
                        border: "none",
                        borderRadius: "5px",
                        cursor: "pointer",
                      }}
                    >
                      Cancel
                    </button>
                    <button
                      onClick={handleCreateTrip}
                      disabled={loading || !from || !to}
                      style={{
                        padding: "10px 20px",
                        fontSize: "16px",
                        backgroundColor: loading || !from || !to ? "#ccc" : "#0070f3",
                        color: "white",
                        border: "none",
                        borderRadius: "5px",
                        cursor: loading || !from || !to ? "not-allowed" : "pointer",
                      }}
                    >
                      {loading ? "Generating..." : "Generate Trip"}
                    </button>
                  </div>
                </div>
              </div>
            )}
          </div>
        ) : (
          <div>
            <p className={styles.description}>
              Please <Link href="/login">sign in</Link> or{" "}
              <Link href="/signup">sign up</Link> to continue.
            </p>
          </div>
        )}
      </main>
    </div>
  );
};

export default Home;
