import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { useSession, signOut } from "@/lib/auth-client";
import { useState, useEffect } from "react";
import styles from "../styles/Home.module.css";

interface Trip {
  id: string;
  name: string;
  destinations: string;
  startDate: string | null;
  endDate: string | null;
  travellers: string | null;
  pace: string | null;
  budget: string | null;
  interests: string | null;
  createdAt: string;
}

const Home: NextPage = () => {
  const { data: session, isPending } = useSession();
  const router = useRouter();
  const [name, setName] = useState("");
  const [destinations, setDestinations] = useState("");
  const [startDate, setStartDate] = useState("");
  const [endDate, setEndDate] = useState("");
  const [travellers, setTravellers] = useState("");
  const [pace, setPace] = useState("balanced");
  const [budget, setBudget] = useState("");
  const [interests, setInterests] = useState("");
  const [mustSees, setMustSees] = useState("");
  const [avoid, setAvoid] = useState("");
  const [mobilityConstraints, setMobilityConstraints] = useState("");
  const [travelModes, setTravelModes] = useState("");
  const [loading, setLoading] = useState(false);
  const [showModal, setShowModal] = useState(false);
  const [trips, setTrips] = useState<Trip[]>([]);
  const [loadingTrips, setLoadingTrips] = useState(false);

  useEffect(() => {
    if (session?.user) {
      fetchTrips();
    }
  }, [session]);

  const fetchTrips = async () => {
    setLoadingTrips(true);
    try {
      const response = await fetch("/api/trips/list");
      const result = await response.json();
      if (result.success) {
        setTrips(result.trips);
      }
    } catch (error) {
      console.error("Error fetching trips:", error);
    } finally {
      setLoadingTrips(false);
    }
  };

  const handleSignOut = async () => {
    await signOut();
  };

  const handleCreateTrip = async () => {
    setLoading(true);
    try {
      const response = await fetch("/api/trips/create", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ 
          name,
          destinations,
          startDate,
          endDate,
          travellers,
          pace,
          budget,
          interests,
          mustSees,
          avoid,
          mobilityConstraints,
          travelModes
        }),
      });

      const result = await response.json();
      
      if (result.success) {
        setShowModal(false);
        setName("");
        setDestinations("");
        setStartDate("");
        setEndDate("");
        setTravellers("");
        setPace("balanced");
        setBudget("");
        setInterests("");
        setMustSees("");
        setAvoid("");
        setMobilityConstraints("");
        setTravelModes("");
        fetchTrips();
        router.push(`/canvas?tripId=${result.tripId}`);
      } else {
        alert("Failed to generate travel flow");
      }
    } catch (error) {
      console.error("Error:", error);
      alert("An error occurred");
    } finally {
      setLoading(false);
    }
  };

  const handleViewTrip = (tripId: string) => {
    router.push(`/canvas?tripId=${tripId}`);
  };

  const handleDeleteTrip = async (tripId: string, tripName: string, e: React.MouseEvent) => {
    e.stopPropagation();
    
    if (!confirm(`Are you sure you want to delete "${tripName}"?`)) {
      return;
    }

    try {
      const response = await fetch("/api/trips/delete", {
        method: "DELETE",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ id: tripId }),
      });

      const result = await response.json();
      
      if (result.success) {
        fetchTrips();
      } else {
        alert("Failed to delete trip");
      }
    } catch (error) {
      console.error("Error deleting trip:", error);
      alert("An error occurred while deleting");
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Next.js on Replit!</h1>

        {isPending ? (
          <p className={styles.description}>Loading...</p>
        ) : session?.user ? (
          <div>
            <p className={styles.description}>
              Welcome, {String(session.user.name || session.user.email || "User")}!
            </p>
            <div style={{ marginTop: "20px", display: "flex", gap: "10px", justifyContent: "center" }}>
              <button
                onClick={() => setShowModal(true)}
                style={{
                  padding: "12px 30px",
                  fontSize: "16px",
                  backgroundColor: "#0070f3",
                  color: "white",
                  border: "none",
                  borderRadius: "5px",
                  cursor: "pointer",
                  fontWeight: "600",
                }}
              >
                New Trip
              </button>
              <button
                onClick={handleSignOut}
                style={{
                  padding: "10px 20px",
                  fontSize: "16px",
                  backgroundColor: "#ff0000",
                  color: "white",
                  border: "none",
                  borderRadius: "5px",
                  cursor: "pointer",
                }}
              >
                Sign Out
              </button>
            </div>

            {/* Trips List */}
            <div style={{ marginTop: "40px", maxWidth: "800px", margin: "40px auto" }}>
              <h2 style={{ marginBottom: "20px", color: "#333" }}>Your Trips</h2>
              {loadingTrips ? (
                <p>Loading trips...</p>
              ) : trips.length === 0 ? (
                <p style={{ color: "#666" }}>No trips yet. Create your first trip!</p>
              ) : (
                <div style={{ display: "grid", gap: "15px" }}>
                  {trips.map((trip) => (
                    <div
                      key={trip.id}
                      onClick={() => handleViewTrip(trip.id)}
                      style={{
                        padding: "20px",
                        backgroundColor: "#fff",
                        border: "1px solid #ddd",
                        borderRadius: "8px",
                        cursor: "pointer",
                        transition: "all 0.2s",
                        boxShadow: "0 2px 4px rgba(0,0,0,0.05)",
                        position: "relative",
                      }}
                      onMouseEnter={(e) => {
                        e.currentTarget.style.boxShadow = "0 4px 12px rgba(0,0,0,0.1)";
                        e.currentTarget.style.borderColor = "#0070f3";
                      }}
                      onMouseLeave={(e) => {
                        e.currentTarget.style.boxShadow = "0 2px 4px rgba(0,0,0,0.05)";
                        e.currentTarget.style.borderColor = "#ddd";
                      }}
                    >
                      <button
                        onClick={(e) => handleDeleteTrip(trip.id, trip.name, e)}
                        style={{
                          position: "absolute",
                          top: "15px",
                          right: "15px",
                          padding: "6px 12px",
                          fontSize: "12px",
                          backgroundColor: "#ff4444",
                          color: "white",
                          border: "none",
                          borderRadius: "4px",
                          cursor: "pointer",
                          fontWeight: "500",
                          transition: "background-color 0.2s",
                        }}
                        onMouseEnter={(e) => {
                          e.currentTarget.style.backgroundColor = "#cc0000";
                        }}
                        onMouseLeave={(e) => {
                          e.currentTarget.style.backgroundColor = "#ff4444";
                        }}
                      >
                        Delete
                      </button>
                      <h3 style={{ margin: "0 0 10px 0", color: "#333", paddingRight: "80px" }}>{trip.name}</h3>
                      <p style={{ margin: "5px 0", color: "#666", fontSize: "14px" }}>
                        <strong>Destinations:</strong> {trip.destinations}
                      </p>
                      {trip.startDate && trip.endDate && (
                        <p style={{ margin: "5px 0", color: "#666", fontSize: "14px" }}>
                          <strong>Dates:</strong> {new Date(trip.startDate).toLocaleDateString()} - {new Date(trip.endDate).toLocaleDateString()}
                        </p>
                      )}
                      {trip.travellers && (
                        <p style={{ margin: "5px 0", color: "#666", fontSize: "14px" }}>
                          <strong>Travellers:</strong> {trip.travellers}
                        </p>
                      )}
                      {trip.interests && (
                        <p style={{ margin: "5px 0", color: "#666", fontSize: "14px" }}>
                          <strong>Interests:</strong> {trip.interests}
                        </p>
                      )}
                      <div style={{ display: "flex", gap: "10px", marginTop: "8px" }}>
                        {trip.pace && (
                          <span style={{ 
                            padding: "3px 8px", 
                            fontSize: "11px", 
                            backgroundColor: "#e8f4f8", 
                            color: "#0066cc",
                            borderRadius: "3px",
                            fontWeight: "500"
                          }}>
                            {trip.pace}
                          </span>
                        )}
                        {trip.budget && (
                          <span style={{ 
                            padding: "3px 8px", 
                            fontSize: "11px", 
                            backgroundColor: "#f0f8e8", 
                            color: "#2d7a2d",
                            borderRadius: "3px",
                            fontWeight: "500"
                          }}>
                            {trip.budget}
                          </span>
                        )}
                      </div>
                      <p style={{ margin: "10px 0 0 0", color: "#999", fontSize: "12px" }}>
                        Created: {new Date(trip.createdAt).toLocaleDateString()}
                      </p>
                    </div>
                  ))}
                </div>
              )}
            </div>

            {showModal && (
              <div
                style={{
                  position: "fixed",
                  top: 0,
                  left: 0,
                  right: 0,
                  bottom: 0,
                  backgroundColor: "rgba(0, 0, 0, 0.5)",
                  display: "flex",
                  justifyContent: "center",
                  alignItems: "center",
                  zIndex: 1000,
                }}
                onClick={() => setShowModal(false)}
              >
                <div
                  style={{
                    backgroundColor: "white",
                    padding: "30px",
                    borderRadius: "10px",
                    maxWidth: "600px",
                    width: "90%",
                    maxHeight: "85vh",
                    overflowY: "auto",
                    boxShadow: "0 4px 20px rgba(0, 0, 0, 0.2)",
                  }}
                  onClick={(e) => e.stopPropagation()}
                >
                  <h2 style={{ marginTop: 0, marginBottom: "20px", color: "#333" }}>
                    Plan Your Trip
                  </h2>

                  <div style={{ marginBottom: "15px" }}>
                    <input
                      type="text"
                      placeholder="Trip Name (optional)"
                      value={name}
                      onChange={(e) => setName(e.target.value)}
                      style={{
                        width: "100%",
                        padding: "10px",
                        fontSize: "14px",
                        borderRadius: "5px",
                        border: "1px solid #ccc",
                      }}
                    />
                  </div>

                  <div style={{ marginBottom: "15px" }}>
                    <input
                      type="text"
                      placeholder="Destination(s) (e.g., Paris, Rome, Barcelona)"
                      value={destinations}
                      onChange={(e) => setDestinations(e.target.value)}
                      style={{
                        width: "100%",
                        padding: "10px",
                        fontSize: "14px",
                        borderRadius: "5px",
                        border: "1px solid #ccc",
                      }}
                    />
                  </div>

                  <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "10px", marginBottom: "15px" }}>
                    <div>
                      <label style={{ display: "block", marginBottom: "5px", fontSize: "12px", color: "#666" }}>
                        Start Date
                      </label>
                      <input
                        type="date"
                        value={startDate}
                        onChange={(e) => setStartDate(e.target.value)}
                        style={{
                          width: "100%",
                          padding: "10px",
                          fontSize: "14px",
                          borderRadius: "5px",
                          border: "1px solid #ccc",
                        }}
                      />
                    </div>
                    <div>
                      <label style={{ display: "block", marginBottom: "5px", fontSize: "12px", color: "#666" }}>
                        End Date
                      </label>
                      <input
                        type="date"
                        value={endDate}
                        onChange={(e) => setEndDate(e.target.value)}
                        style={{
                          width: "100%",
                          padding: "10px",
                          fontSize: "14px",
                          borderRadius: "5px",
                          border: "1px solid #ccc",
                        }}
                      />
                    </div>
                  </div>

                  <div style={{ marginBottom: "15px" }}>
                    <input
                      type="text"
                      placeholder="Number of Travellers (e.g., 2 adults, 1 child)"
                      value={travellers}
                      onChange={(e) => setTravellers(e.target.value)}
                      style={{
                        width: "100%",
                        padding: "10px",
                        fontSize: "14px",
                        borderRadius: "5px",
                        border: "1px solid #ccc",
                      }}
                    />
                  </div>

                  <div style={{ marginBottom: "15px" }}>
                    <label style={{ display: "block", marginBottom: "5px", fontSize: "12px", color: "#666" }}>
                      Travel Pace
                    </label>
                    <select
                      value={pace}
                      onChange={(e) => setPace(e.target.value)}
                      style={{
                        width: "100%",
                        padding: "10px",
                        fontSize: "14px",
                        borderRadius: "5px",
                        border: "1px solid #ccc",
                        backgroundColor: "white",
                      }}
                    >
                      <option value="relaxed">Relaxed</option>
                      <option value="balanced">Balanced</option>
                      <option value="packed">Packed</option>
                    </select>
                  </div>

                  <div style={{ marginBottom: "15px" }}>
                    <input
                      type="text"
                      placeholder="Budget (e.g., $3000, moderate)"
                      value={budget}
                      onChange={(e) => setBudget(e.target.value)}
                      style={{
                        width: "100%",
                        padding: "10px",
                        fontSize: "14px",
                        borderRadius: "5px",
                        border: "1px solid #ccc",
                      }}
                    />
                  </div>

                  <div style={{ marginBottom: "15px" }}>
                    <input
                      type="text"
                      placeholder="Interests (e.g., food, art, history, adventure)"
                      value={interests}
                      onChange={(e) => setInterests(e.target.value)}
                      style={{
                        width: "100%",
                        padding: "10px",
                        fontSize: "14px",
                        borderRadius: "5px",
                        border: "1px solid #ccc",
                      }}
                    />
                  </div>

                  <div style={{ marginBottom: "15px" }}>
                    <input
                      type="text"
                      placeholder="Must-See Places (optional)"
                      value={mustSees}
                      onChange={(e) => setMustSees(e.target.value)}
                      style={{
                        width: "100%",
                        padding: "10px",
                        fontSize: "14px",
                        borderRadius: "5px",
                        border: "1px solid #ccc",
                      }}
                    />
                  </div>

                  <div style={{ marginBottom: "15px" }}>
                    <input
                      type="text"
                      placeholder="Things to Avoid (optional)"
                      value={avoid}
                      onChange={(e) => setAvoid(e.target.value)}
                      style={{
                        width: "100%",
                        padding: "10px",
                        fontSize: "14px",
                        borderRadius: "5px",
                        border: "1px solid #ccc",
                      }}
                    />
                  </div>

                  <div style={{ marginBottom: "15px" }}>
                    <input
                      type="text"
                      placeholder="Mobility Constraints (optional)"
                      value={mobilityConstraints}
                      onChange={(e) => setMobilityConstraints(e.target.value)}
                      style={{
                        width: "100%",
                        padding: "10px",
                        fontSize: "14px",
                        borderRadius: "5px",
                        border: "1px solid #ccc",
                      }}
                    />
                  </div>

                  <div style={{ marginBottom: "20px" }}>
                    <input
                      type="text"
                      placeholder="Travel Mode Preferences (e.g., train, car, walking)"
                      value={travelModes}
                      onChange={(e) => setTravelModes(e.target.value)}
                      style={{
                        width: "100%",
                        padding: "10px",
                        fontSize: "14px",
                        borderRadius: "5px",
                        border: "1px solid #ccc",
                      }}
                    />
                  </div>
                  <div style={{ display: "flex", gap: "10px", justifyContent: "flex-end" }}>
                    <button
                      onClick={() => setShowModal(false)}
                      style={{
                        padding: "10px 20px",
                        fontSize: "16px",
                        backgroundColor: "#ccc",
                        color: "#333",
                        border: "none",
                        borderRadius: "5px",
                        cursor: "pointer",
                      }}
                    >
                      Cancel
                    </button>
                    <button
                      onClick={handleCreateTrip}
                      disabled={loading || !destinations}
                      style={{
                        padding: "10px 20px",
                        fontSize: "16px",
                        backgroundColor: loading || !destinations ? "#ccc" : "#0070f3",
                        color: "white",
                        border: "none",
                        borderRadius: "5px",
                        cursor: loading || !destinations ? "not-allowed" : "pointer",
                      }}
                    >
                      {loading ? "Generating..." : "Generate Trip"}
                    </button>
                  </div>
                </div>
              </div>
            )}
          </div>
        ) : (
          <div>
            <p className={styles.description}>
              Please <Link href="/login">sign in</Link> or{" "}
              <Link href="/signup">sign up</Link> to continue.
            </p>
          </div>
        )}
      </main>
    </div>
  );
};

export default Home;
